spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskapp
    username: taskapp_admin
    password: taskapp_admin
    initialization-mode: never
  flyway:
    placeholder-replacement: false
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    user: taskapp_admin
    password: taskapp_admin
#    locations: classpath:db/
  jpa:
#    hibernate:
#      ddl-auto: update
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        default-schema: erply
        format_sql: true
#        show_sql: true
        generate_statistics: false

