spring:
  flyway:
    enabled: false
  datasource:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        default-schema: taskapp
        format_sql: true
        show_sql: true
        generate_statistics: false
